landing page copy update
City-of-Lincoln-Council/housing-repairs-online-frontend pull request #11
Opened 2021-10-11 17:17 UTC by elena-vi

Updated copy on landing page to reflect new designs

![screenshot-localhost_3000-2021 10 11-18_16_15](https://user-images.githubusercontent.com/8051117/136829673-4e082447-87a2-467a-b271-dc6521df2c55.png)

2021-10-11 17:18 UTC, elena-vi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Landing Page (MVP)](https://trello.com/c/TTnaXdE8/163-landing-page-mvp)

2021-10-12 08:42 UTC, Bhavesh-Patel requested changes
Couple of small differences between the prototype and production.

2021-10-12 08:42 UTC, Bhavesh-Patel commented on src/pages/landingPage.js
>            <H1>Report a repair</H1>
Title from [prototype](https://southwark-repairs-alpha-master.herokuapp.com/beta/v2/) is "Request a repair"
```suggestion
          <H1>Request a repair</H1>
```

2021-10-12 08:42 UTC, Bhavesh-Patel commented on src/pages/landingPage.js
> +    <Link href="https://www.lincoln.gov.uk/contact-1/get-touch">
In the [prototype](https://southwark-repairs-alpha-master.herokuapp.com/beta/v2/) clicking the "contact details page" link opens the url in a new page.
```suggestion
    <Link href="https://www.lincoln.gov.uk/contact-1/get-touch" target="_blank">
```

2021-10-13 08:12 UTC, Bhavesh-Patel approved these changes

2021-10-13 08:20 UTC, merged