Match prototype v3
City-of-Lincoln-Council/housing-repairs-online-frontend pull request #15
Opened 2021-10-29 09:57 UTC by maysakanoni

Update the landing, emergency, communal, postcode and address pages to match the [v3 prototype](https://southwark-repairs-alpha-master.herokuapp.com/beta/v3/).

2021-11-01 12:09 UTC, Bhavesh-Patel reviewed
Some changes required to reflect v3 prototype

2021-11-01 12:09 UTC, Bhavesh-Patel commented on src/components/reportRepair/address.js
>            <Link as={RouterLink} to="not-eligible">I can&apos;t find my address on this list</Link>
The title/headline of this page is no longer "Where is the repair located?" and should be changed to "Select an address".

2021-11-01 12:09 UTC, Bhavesh-Patel commented on src/components/reportRepair/postcode.js
> +        buttonText={'Select your addresses'}
The button text should be "Select your address"
```suggestion
        buttonText={'Select your address'}
```

2021-11-01 12:09 UTC, Bhavesh-Patel commented on src/components/reportRepair/communal.js
The "continue" button text should now be "Provide your postcode"

2021-11-22 09:34 UTC, Bhavesh-Patel commented on src/pages/landingPage.js
> +          <hr></hr>
Opening hours in the prototype are different to the MVP:
Differences:

- Prototype has `Wednesday 10am - 4.30pm` and MVP has `Wednesday 9am - 4.30pm` 
- Prototype has `Thursday 9am - 5pm` and MVP has `Thursday 10am - 5pm`

2021-11-22 10:19 UTC, Bhavesh-Patel requested changes
The phone number format is inconsistent in the prototype - there are both 5-3-3 and 5-6 digit formats.

UX designer has confirmed the we should consistently use 5-6 format, i.e. `01522 534747`

See specific comments for the changes needed.

Some previous comments also need addressing.

2021-11-22 10:19 UTC, Bhavesh-Patel commented on src/components/reportRepair/emergencyRepair.js
> +          For non-emergency requests, call **01522 873 333**
Please update telephone number format to 5-6 digits, i.e. `01522 534747`

2021-11-22 10:47 UTC, maysakanoni commented on src/components/reportRepair/emergencyRepair.js
> +        <Paragraph>For non-emergency requests, call **01522 873333**</Paragraph>
The opening times are there, are they in the wrong place?

2021-11-22 10:49 UTC, maysakanoni commented on src/components/reportRepair/emergencyRepair.js
> +          emergency.
Its still in [this](https://lincoln-repairs.herokuapp.com/beta/v3/emergency) prototype

2021-11-22 10:57 UTC, closed without merging