change priority list options
City-of-Lincoln-Council/housing-repairs-online-frontend pull request #22
Opened 2021-11-23 13:52 UTC by elena-vi

2021-11-23 13:52 UTC, elena-vi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rework - Emergency repair identification (priority list page + options) (MVP)](https://trello.com/c/ng7iuRnL/228-rework-emergency-repair-identification-priority-list-page-options-mvp)

2021-11-23 14:55 UTC, Bhavesh-Patel requested changes
The tests are brittle due to reliance upon copy/displayed text for finding elements.
Can they be made less brittle? Perhaps using test id's?

Think we've discussed previously, but wanted to revisit in case anything had changed.

2021-11-23 14:55 UTC, Bhavesh-Patel commented on compoments/radioFieldSet.js
> +                    <div className="govuk-radios__item" key={i}>
This block (lines 62-70) and the block in the else clause (lines 75-83) are essentially repeated.
Try to remove the duplication.

2021-11-23 14:55 UTC, Bhavesh-Patel commented on compoments/radioFieldSet.js
> +              if (this.includeOrDivider && i == (this.options.length - 1)) {
This check is being performed for every item, but it'll only be true for the last item - consider refactoring to improve flow of code.

2021-11-23 14:55 UTC, Bhavesh-Patel commented on compoments/radioFieldSet.js
> +                    <div className="govuk-radios__divider">or</div>
This block (lines 62-70) and the block in the else clause (lines 75-83) are equivalent.
Try to refactor to remove duplication of code.

2021-11-23 14:55 UTC, Bhavesh-Patel commented on compoments/radioFieldSet.js
> +              if (this.includeOrDivider && i == (this.options.length - 1)) {
This check is performed for every item in `options`, but will only be true once - for the last item.
Is it possible to improve the flow to remove the redundant checks?

2021-11-24 09:12 UTC, Bhavesh-Patel approved these changes

2021-11-24 09:32 UTC, merged