add walls floor ceiling options
City-of-Lincoln-Council/housing-repairs-online-frontend pull request #45
Opened 2022-01-19 15:59 UTC by elena-vi

2022-01-19 16:43 UTC, elena-vi commented
![](https://github.trello.services/images/mini-trello-icon.png) [Identify repair - Walls/Floor/Ceiling (Kitchen/Bathroom/Bedroom/Living areas)](https://trello.com/c/WqO5tPy1/152-identify-repair-walls-floor-ceiling-kitchen-bathroom-bedroom-living-areas)

2022-01-20 09:43 UTC, Bhavesh-Patel requested changes

2022-01-20 09:43 UTC, Bhavesh-Patel commented on pages/report-repair/[route].js
> +    walls: { value: 'wallsFloorsCeiling', title: 'Walls, floor or ceiling, excluding damp' }
The current name of `walls` could be misleading when taken out of context and assumed to only be for "walls", whereas it includes floor and ceiling too.
Please rename to represent all the areas it encompasses.
```suggestion
    wallsFloorAndCeiling: { value: 'wallsFloorsCeiling', title: 'Walls, floor or ceiling, excluding damp' }
```

2022-01-20 09:43 UTC, Bhavesh-Patel commented on pages/report-repair/[route].js
> +    case 'wall-problems':
Same as other comment - please rename to represent all the areas it encompasses.
```suggestion
    case 'wall-floor-ceiling-problems':
```

2022-01-20 09:43 UTC, Bhavesh-Patel commented on pages/report-repair/[route].js
> +    {params: { route: 'wall-problems'} },
After renaming in other comment, this would also need renaming
```suggestion
    {params: { route: 'wall-floor-ceiling-problems'} },
```

2022-01-20 10:08 UTC, Bhavesh-Patel approved these changes

2022-01-20 10:08 UTC, merged